spring:
   application:
     name: DOCKER_-PROFILE
   datasource:
     url: jdbc:postgresql://postgres:5432/url_shortner
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}

   data:
     redis:
       host: redis
       port: 6379

   logging:
    level: 
      org.springbootframework.boot.context.config: DEBUG